/**
 * @fileoverview gRPC-Web generated client stub for gamepb
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.4.1
// 	protoc              v3.21.12
// source: game.proto


/* eslint-disable */
// @ts-nocheck



const grpc = {};
grpc.web = require('grpc-web');

const proto = {};
proto.gamepb = require('./game_pb.js');

/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.gamepb.GameClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.gamepb.GamePromiseClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.gamepb.GetPlayerRequest,
 *   !proto.gamepb.GetPlayerResponse>}
 */
const methodDescriptor_Game_GetPlayer = new grpc.web.MethodDescriptor(
  '/gamepb.Game/GetPlayer',
  grpc.web.MethodType.SERVER_STREAMING,
  proto.gamepb.GetPlayerRequest,
  proto.gamepb.GetPlayerResponse,
  /**
   * @param {!proto.gamepb.GetPlayerRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.gamepb.GetPlayerResponse.deserializeBinary
);


/**
 * @param {!proto.gamepb.GetPlayerRequest} request The request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!grpc.web.ClientReadableStream<!proto.gamepb.GetPlayerResponse>}
 *     The XHR Node Readable Stream
 */
proto.gamepb.GameClient.prototype.getPlayer =
    function(request, metadata) {
  return this.client_.serverStreaming(this.hostname_ +
      '/gamepb.Game/GetPlayer',
      request,
      metadata || {},
      methodDescriptor_Game_GetPlayer);
};


/**
 * @param {!proto.gamepb.GetPlayerRequest} request The request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!grpc.web.ClientReadableStream<!proto.gamepb.GetPlayerResponse>}
 *     The XHR Node Readable Stream
 */
proto.gamepb.GamePromiseClient.prototype.getPlayer =
    function(request, metadata) {
  return this.client_.serverStreaming(this.hostname_ +
      '/gamepb.Game/GetPlayer',
      request,
      metadata || {},
      methodDescriptor_Game_GetPlayer);
};


module.exports = proto.gamepb;

